### ISSUE TITLE
Not showing correct closest study group.

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/study-group-directory#9]
I live kind of near Midland, Michigan. However, when I go to the webpage it shows that my closest group is in Midland, Texas. These cities are not close to each other.

**Comment by ginoskotheon** [comment]
@beaucarnes could you try it now? When I paired the coordinates together, I used [GPS Visualizer](http://www.gpsvisualizer.com/geocoder/) and it matched up cities to coordinates. It put Midland, Michigan's coord's instead of Texas.

 I think this might end up being a common problem. I figured it was easier to get 90% of them right and have people find mistakes than try to find all 1700+ coords one at a time.

**Comment by beaucarnes** [comment]
It's better now, but not perfect. I live _near_ Midland but I actually live in Saginaw. It is showing that my closest group is in Bad Axe which is 66 miles from me. There is also a study group in Flint which is only 37 miles from me and I think the one in Flint should show as the closest group instead of Bad Axe.

**Comment by ginoskotheon** [comment]
@beaucarnes should be fixed now.

**Comment by beaucarnes** [comment]
It is! Thanks.
