### ISSUE TITLE
Allow multiple URLs for each group.

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/study-group-directory#90]
Presently we only have one url for each group in the directory, and its exclusively Facebook, but I am aware that some groups are using different sites (examples: Meetup, Google Groups, WeChat, Slack) and some groups have more than one site they use for their group.

I suggest we allow entries to list any and all sites they have a presence on and return these as links after the location name. (Optionally, you could create a whitelist of approved sites to provide some protection to group members in case of malicious intent by someone setting up a group or just a poor choice of site.)

**Comment by johnkennedy9147** [comment]
@QuincyLarson Can we start adding non-facebook urls to the study group directory? see #135

**Comment by QuincyLarson** [comment]
@johnkennedy9147 Sure - we can add whatever URL they want. I just added a new URL for Houston that leads to their own website, which has links to their Facebook group, Meetup.com group, and Slack chat.

We should only have one link per group, but which platform that links to isn't that important. For example, in China, everyone uses WeChat instead of Facebook.
